// Run from the repository root: node interface/tests/notebook.mjs
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),N=require('../render/notebook.js');
const config={available:true,root:'capture',guide:'README.md',groups:[{path:'.',label:'General'}],sheet_names:{'notes.md':'Notas'}};
const files=[{root:'capture',path:'README.md'},{root:'capture',path:'loose.md'}, {root:'capture',path:'lab/alpha/notes.md'}, {root:'capture',path:'other/alpha/notes.md'},{root:'capture',path:'lab/alpha/ideas.md'}, {root:'private',path:'loose.md'}];
const tree={notebook:config,files},catalog=N.files(tree);
assert.equal(catalog.length,5);
assert.equal(N.files({files}).length,0,'No guessed root');
const projects=[{lab:'lab',name:'alpha'},{lab:'other',name:'alpha'}];
const groups=N.groups(catalog,config,projects);
assert.equal(groups.length,3);
assert.equal(groups.flatMap(g=>g.files).length+1,catalog.length,'Every sheet and the guide are reachable exactly once');
assert.equal(groups.find(g=>g.path==='lab/alpha').project,projects[0]);
assert.equal(groups.find(g=>g.path==='other/alpha').project,projects[1]);
assert.equal(N.groups(catalog,config,[...projects,projects[0]]).find(g=>g.path==='lab/alpha').project,null);
assert.equal(N.label(catalog[2],config),'Notas');
const hits=[{root:'capture',path:'lab/alpha/notes.md',line:52,text:'N-52'},{root:'private',path:'loose.md',line:1,text:'N-52'}];
assert.equal(N.results(catalog,config,{q:'N-52'},hits).length,1);
assert.equal(N.results(catalog,config,{q:'N-52',folder:'other/alpha'},hits).length,0);
const loc={path:'other/alpha/notes.md',folder:'other/alpha',q:'N-52 %',anchor:'a & b',line:52};
assert.deepEqual(N.location(new URLSearchParams(N.route(loc).split('?')[1])),loc);
console.log('Notebook: complete catalog, exact groups/projects, scoped search and route identity pass.');
const L=require('../render/library.js'),md=require('../vendor/markdown-it/markdown-it.umd.min.js'),katex=require('../vendor/katex/katex.min.js');
const rendered=L.render('- `N-9` First capture\n\n[Other](../beta/notes.md)\n', {root:'capture',path:'team/alpha/notes.md'},[{root:'capture',path:'team/beta/notes.md'}],{markdownit:md,katex},{sourceLines:true,lineOffset:4,noteRoute:({path,anchor})=>N.route({path,anchor})});
assert.match(rendered.html,/data-source-line="5"/);
assert.match(rendered.html,/#\/notebook\?note=team%2Fbeta%2Fnotes.md/);
assert.equal(N.results(catalog,config,{q:'N-52'},[...hits,{root:'capture',path:'other/alpha/notes.md',line:2,text:'N-52'}]).length,2,'Repeated identifiers in distinct sheets remain separate results');
console.log('Notebook source-line offsets, internal reader links and duplicate identifiers pass.');
assert.equal(N.matches('N-900 next capture','N-90'),false);
assert.equal(N.matches('N-90-extra','N-90'),false);
assert.equal(N.matches('éN-90','N-90'),false);
assert.equal(N.matches('`N-90` target','N-90'),true);
assert.equal(N.matches('Configuración','configuracion'),true);
assert.equal(N.results([{root:'capture',path:'N-900.md'}],config,{q:'N-90'}).length,0);
assert.equal(N.matchLine('# Notes\n\nInserted\n\nN-90 capture\n','N-90',3),5,'Inserted paragraphs must not move the highlight onto unrelated prose');
assert.equal(N.matchLine('# Notes\n\nCapture removed\n','N-90',3),0,'Removed text has no highlight');
assert.equal(N.matchLine('N-900 unrelated\nN-90 capture','N-90',1),2);
const blocks=L.render('Before\n\n```text\nneedle\n```\n\n$$x^2$$\n',{root:'capture',path:'notes.md'},[],{markdownit:md,katex},{sourceLines:true});
assert.match(blocks.html,/<div data-source-line="3" data-source-end="5"><pre>/,'Code search targets its complete block');
assert.match(blocks.html,/<div data-source-line="7" data-source-end="7">/,'Display math also has source coordinates');
console.log('Notebook exact identifiers and search targets surviving source edits pass.');
